
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.ufcg.compiladores;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RIGHT_PARENTHESIS = 6;
  public static final int PROGRAM = 2;
  public static final int COLON = 8;
  public static final int LEFT_PARENTHESIS = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int SEMICOLON = 9;
  public static final int IDENTIFIER = 11;
  public static final int FULL_STOP = 10;
  public static final int END = 4;
  public static final int BEGIN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "BEGIN",
  "END",
  "LEFT_PARENTHESIS",
  "RIGHT_PARENTHESIS",
  "COMMA",
  "COLON",
  "SEMICOLON",
  "FULL_STOP",
  "IDENTIFIER"
  };
}

